### PR TITLE
Add speed control mode

### PR DESCRIPTION
**Pull request by Thomio-Watanabe**
Add speed mode to control simulated thrusters

### CODE REVIEW

**Comment by doudou** [comment]
I'm not really sure about the general usefulness of this. What's the idea ?

**Comment by Thomio-Watanabe** [comment]
@rafaelsaback and @joaobrittoneto have a thruster model based on speed, so they asked me to create this.
Saback made some tests this afternoon and it seems fine for him.

**Comment by Thomio-Watanabe** [comment]
Maybe I should rename **input** to **speed** in:

```
effort = alpha_positive * input * input;
```

**Comment by rafaelsaback** [comment]
Sylvain, the idea is to make the control signal in the simulation as similar as possible to the real one, which is good from a control point of view. In the real vehicle, the control signal sent to the thrusters is their rotation speed (each one of them has an internal control loop). The provider of the thrusters performed some experiments that relates the thruster rotation to the generated force, so we have a reasonable model of them.

**Comment by rafaelsaback** [comment]
Small correction:

effort = alpha_positive * abs(input) * input

**Comment by rafaelsaback** [comment]
Maybe we should consider using "rotation" or "thruster_rotation" instead of "speed", so no one misconfuse it with the vehicle's speed.

**Comment by Thomio-Watanabe** [comment]
Amend last commit: 
- rename local variable to rotation

**Comment by doudou** [comment]
@rafaelsaback: While I do understand (now) the usefulness of it from a code point of view (more choice ...), I am wondering about the usefulness of it from our point of view. Having different systems is actually a good thing. So, how having to target effort instead of rotation in this case would impact your pipeline ?

How do you deal with the speed-to-effort mapping in your control/identification strategies ?

**Comment by rafaelsaback** [comment]
Well, in general we could say that the more realistic the simulation, the better for testing control algorithms. Being more specific, once we emulate the thruster dynamics in the simulation:

1) When we have a reasonable  model of the vehicle (I know, this might be tricky, but we will sort this out), we can tune the PIDs based on the simulation. And then, when we go to the real world, we have a very good starting point for the PID tuning that might even be good enough. If we always consider a thruster-effort-based control during the simulations, we might have some problems in real experiments because the real control signal is based on the rotation speed of the thrusters instead.

2) We can test new control algorithms and identification methods, and once the control signal is similar, later we can test them for real without expecting many suprises.

Besides this enhancements for the simulation, we can also include the inverse of the thruster modelling inside our control strategy (a piece of code that would convert the thrusters' forces into correspondent rotation speeds). Doing so, we can :

1) Cancel the nonlinearity of the thruster dynamics, which can improve the control performance (the more linear the system, the better for the control)

2) We can have a control system with a complete physical meaning of each link, like:

```
position (vehicle) -> speed (vehicle) -> forces and moments (vehicle) -> forces (thrusters) -> rotation speed (thrusters)
```

This allows us to have a better understanding about what is going on with the control, since the interpretation of each link is straightforward. The convertion of the thrusters' forces to its correspondent rotation speeds could be done inside the AccelerationController (my current preference, because we already have the thrusters' saturation implemented inside it), inside the thruster driver or in a new task between these two guys. The equation would basically be:

```
rotation = +/- sqrt(desiredForce/alpha)
```

**Comment by doudou** [comment]
About (1): I won't dwelve here on the feasibility. Because I personally don't even believe that it would even improve the overall development workflow. It's one of these ideas that sound nice, but require a lot of effort for very little improvement. What's really needed IMO are ways (i.e. tools that is GUIs and/or auto-tuning algorithms) to make controller tuning as painless as possible (note that I used the term "painless", not "straightforward").

About the rest: We will of course need to have pieces of code that handle the thruster_force-to-thruster_rotation, and that better be tested. However, since everything is _simulated_, what we will end up is:

```
AccelerationController
    -> thruster_force-to-thruster_rotation
    -> thruster_rotation-to-thruster_force
    -> physics engine
```

Since _we_ write the code for both force-to-rotation and rotation-to-force, I don't see what the simulation truly allows us to "test" here. Rather write unit-tests for the conversion component than add complexity to the simulation. That would test MUCH better than the simulation would.

As for the identification: same argument. Identification is done offline. Run the force-to-rotation model on the test dataset and feed that to your identification algorithm. _Automatically_ test that it matches the model (getting data from the SDF / thruster model parameters). You get a workflow where you can test identification on different simulated models and identification algorithms _for free_ without ever re-running simulation. And run these tests automatically to check for regressions.

At the end, I prefer having a simulated vehicle that is close but not-that-close to the real system, because it exposes the flaws in the implementation(s) and architecture much better (we get two systems rather than one) without really impacting the actual functionality (if it does, then we _need_ to improve the simulation).

**Comment by rafaelsaback** [comment]
Ok, I see your point.  I totally agree when you say that this change could expose "implementation flaws without really impacting the actual functionality" if we implement and guarantee the proper functionality of the thruster_force-to-thruster_rotation through the unitary tests (and this is pretty much simple).

I've talked to Thomio, and following this way of thinking (making the simulation as leaner as possible and disregarding the thruster dynamics) we could also discard the thrusterRawModel, and keep the thruster effort as the unique input. Is that ok?

**Comment by doudou** [comment]
> I've talked to Thomio, and following this way of thinking (making the simulation as leaner as possible and disregarding the thruster dynamics) we could also discard the thrusterRawModel, and keep the thruster effort as the unique input. Is that ok?

Yes.

**Comment by Thomio-Watanabe** [comment]
Then I'll close this PR and open a new one deleting the thrusterRawModel implementation

**Pull request closed without merging**
